<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CreateMerchantAliasAsyncResultService" targetNamespace="http://webservices.sibsmerchant.com/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://webservices.sibsmerchant.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://webservices.sibsmerchant.com/" schemaLocation="CreateMerchantAliasAsyncResultService_schema1.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://alias.services.merchant.channelmanagermsp.sibs/" schemaLocation="CreateMerchantAliasAsyncResultService_schema2.xsd"/>
    </xsd:schema>
  </types>
  <message name="createAliasResultResponse">
    <part name="parameters" element="tns:createAliasResultResponse">
    </part>
  </message>
  <message name="createAliasResult">
    <part name="parameters" element="tns:createAliasResult">
    </part>
  </message>
  <portType name="CreateMerchantAliasAsyncResult">
    <operation name="createAliasResult">
      <input message="tns:createAliasResult" wsam:Action="http://webservices.sibsmerchant.com/CreateMerchantAliasAsyncResult/createAliasResultRequest">
    </input>
      <output message="tns:createAliasResultResponse" wsam:Action="http://webservices.sibsmerchant.com/CreateMerchantAliasAsyncResult/createAliasResultResponse">
    </output>
    </operation>
  </portType>
  <binding name="CreateMerchantAliasAsyncResultPortBinding" type="tns:CreateMerchantAliasAsyncResult">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="createAliasResult">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CreateMerchantAliasAsyncResultService">
    <port name="CreateMerchantAliasAsyncResultPort" binding="tns:CreateMerchantAliasAsyncResultPortBinding">
      <soap:address location="http://vsarctibd1:9082/client/CreateMerchantAliasAsyncResultService"/>
    </port>
  </service>
</definitions>
